TITLE = "Stop Freezing: English Speaking Confidence Practice"


def build_cindy_script() -> str:
    lines = [
        "Hello and welcome to Cindy Podcast Channel. If you understand English, but you freeze when it is your turn to speak, this practice is for you.",
        "Today, we are going to train your speaking confidence with a calm shadowing practice.",
        "You do not need perfect English. You need useful English that your mouth can say when the pressure starts.",
        "Here is how this practice will work. First, listen to the sentence. Then repeat it out loud. Try to copy my rhythm, my stress, and my calm voice.",
        "Some sentences will be repeated so you can say them again with more confidence.",
        "Do not rush. Do not worry about small mistakes. The goal is to keep speaking.",
        "Take a slow breath. Relax your shoulders. Let us begin.",
        "I do not need perfect English to start.",
        "I do not need perfect English to start.",
        "I can speak slowly and still sound clear.",
        "I can speak slowly and still sound clear.",
        "When I feel nervous, I can take a second.",
        "When I feel nervous, I can take a second.",
        "Give me a second, I know how to say this.",
        "Give me a second, I know how to say this.",
        "This phrase is very useful. It gives you time without going silent.",
        "Say it again with me.",
        "Give me a second, I know how to say this.",
        "I am training my mouth to move in English.",
        "I am training my mouth to move in English.",
        "I am allowed to pause and think.",
        "I am allowed to pause and think.",
        "Let me say that again.",
        "Let me say that again.",
        "Let me say that another way.",
        "Let me say that another way.",
        "These two sentences are powerful because they help you restart.",
        "You do not have to stop the conversation when one sentence feels wrong.",
        "Let me say that another way.",
        "I understand the idea, but I need more practice using it.",
        "I understand the idea, but I need more practice using it.",
        "The main thing is, I want to speak more naturally.",
        "The main thing is, I want to speak more naturally.",
        "The main thing is, I need more time to answer.",
        "The main thing is, I need more time to answer.",
        "Good. Now we will practice short phrases for real speaking moments.",
        "I know what you mean.",
        "I know what you mean.",
        "That makes sense.",
        "That makes sense.",
        "That actually makes sense.",
        "That actually makes sense.",
        "I did not think of it that way.",
        "I did not think of it that way.",
        "Could you say that one more time?",
        "Could you say that one more time?",
        "Sorry, I missed the last part.",
        "Sorry, I missed the last part.",
        "I want to make sure I understood you.",
        "I want to make sure I understood you.",
        "These are not complicated sentences, but they keep the conversation alive.",
        "If you freeze, use one of these phrases instead of disappearing into silence.",
        "Could you say that one more time?",
        "I want to make sure I understood you.",
        "Now let us practice confidence sentences for your mind.",
        "I can make mistakes and still communicate.",
        "I can make mistakes and still communicate.",
        "My English does not have to be perfect to be useful.",
        "My English does not have to be perfect to be useful.",
        "I can answer with a simple sentence first.",
        "I can answer with a simple sentence first.",
        "Then I can add more details.",
        "Then I can add more details.",
        "A simple answer is better than no answer.",
        "A simple answer is better than no answer.",
        "This is a good moment to remember something important. Speaking confidence grows through real practice, not only passive listening.",
        "If you want more real conversation practice, Saloo English helps learners practice everyday English, build confidence, and stop freezing when it is time to speak.",
        "You can find the Saloo English link in the description.",
        "Now come back to the practice with me.",
        "I can start with one clear sentence.",
        "I can start with one clear sentence.",
        "I can add one detail after that.",
        "I can add one detail after that.",
        "For example, I am a little nervous, but I want to try.",
        "For example, I am a little nervous, but I want to try.",
        "I am still learning, but I can explain my idea.",
        "I am still learning, but I can explain my idea.",
        "I need a moment, but I can answer.",
        "I need a moment, but I can answer.",
        "Let us move into natural responses.",
        "That is a good point.",
        "That is a good point.",
        "I agree with you.",
        "I agree with you.",
        "I am not sure, but I think so.",
        "I am not sure, but I think so.",
        "I see your point.",
        "I see your point.",
        "Can I ask you a quick question?",
        "Can I ask you a quick question?",
        "What do you mean by that?",
        "What do you mean by that?",
        "These phrases help you sound present in the conversation.",
        "You are not just listening. You are participating.",
        "Can I ask you a quick question?",
        "What do you mean by that?",
        "Now let us practice when you need to explain yourself.",
        "What I mean is, I need more practice speaking.",
        "What I mean is, I need more practice speaking.",
        "What I am trying to say is, I understand more than I can say.",
        "What I am trying to say is, I understand more than I can say.",
        "It is easier for me to listen than to speak.",
        "It is easier for me to listen than to speak.",
        "But I am getting better little by little.",
        "But I am getting better little by little.",
        "I am getting better little by little.",
        "I am getting better little by little.",
        "Now say these next lines like you are talking to a real person.",
        "I understand, but I need a second to answer.",
        "I understand, but I need a second to answer.",
        "I want to say it clearly.",
        "I want to say it clearly.",
        "Let me think for a moment.",
        "Let me think for a moment.",
        "Okay, I think I can explain it now.",
        "Okay, I think I can explain it now.",
        "That was good. Your voice is learning the path.",
        "Now we will practice a short flow. Listen first, then repeat each line.",
        "I used to freeze when someone asked me a question.",
        "I used to freeze when someone asked me a question.",
        "Now I take a breath and start with a simple answer.",
        "Now I take a breath and start with a simple answer.",
        "If I need time, I say, give me a second.",
        "If I need time, I say, give me a second.",
        "If I make a mistake, I say it another way.",
        "If I make a mistake, I say it another way.",
        "I keep going because communication is the goal.",
        "I keep going because communication is the goal.",
        "Now let us practice a second flow for real conversation pressure.",
        "Someone asks me a question, and I feel nervous.",
        "Someone asks me a question, and I feel nervous.",
        "I do not disappear into silence.",
        "I do not disappear into silence.",
        "I take a breath and answer with one clear idea.",
        "I take a breath and answer with one clear idea.",
        "If I need help, I ask for help.",
        "If I need help, I ask for help.",
        "If I need time, I ask for time.",
        "If I need time, I ask for time.",
        "If I do not understand, I ask a better question.",
        "If I do not understand, I ask a better question.",
        "That is how real speaking works.",
        "That is how real speaking works.",
        "You do not need to know every word before you start speaking.",
        "You need a few strong phrases that help you stay present.",
        "Repeat these practical lines with me.",
        "Can you give me an example?",
        "Can you give me an example?",
        "Can you explain that in a simpler way?",
        "Can you explain that in a simpler way?",
        "I think I understand, but I want to check.",
        "I think I understand, but I want to check.",
        "So you mean the plan changed, right?",
        "So you mean the plan changed, right?",
        "That helps. Thank you.",
        "That helps. Thank you.",
        "Now practice speaking with a calm emotional tone.",
        "I feel nervous, but I can still speak.",
        "I feel nervous, but I can still speak.",
        "I feel unsure, but I can ask a question.",
        "I feel unsure, but I can ask a question.",
        "I feel slow, but I am still improving.",
        "I feel slow, but I am still improving.",
        "I feel more confident when I practice out loud.",
        "I feel more confident when I practice out loud.",
        "Good. These sentences are useful because they sound honest and human.",
        "They do not pretend that speaking is always easy.",
        "They help you continue even when speaking feels uncomfortable.",
        "Excellent. This is the mindset you need for speaking.",
        "Not perfect grammar first. Communication first.",
        "Not fast English first. Clear English first.",
        "Not fear first. Practice first.",
        "Repeat these final confidence lines with me.",
        "I can speak English with a calm voice.",
        "I can speak English with a calm voice.",
        "I can pause without feeling embarrassed.",
        "I can pause without feeling embarrassed.",
        "I can ask someone to repeat.",
        "I can ask someone to repeat.",
        "I can restart my sentence.",
        "I can restart my sentence.",
        "I can explain my idea in simple English.",
        "I can explain my idea in simple English.",
        "I can keep going even when I make a mistake.",
        "I can keep going even when I make a mistake.",
        "Before we finish, remember this. Freezing does not mean your English is bad. It usually means your brain needs more speaking practice, more repetition, and more safe moments to respond.",
        "That is why shadowing works. You repeat useful sentences until they feel familiar in your mouth.",
        "If you want to practice real conversations and build speaking confidence step by step, check Saloo English. The link is in the description.",
        "Thank you for practicing with me today on Cindy Podcast Channel.",
        "Save this practice and repeat it again tomorrow. The second time will feel easier.",
        "Keep speaking, keep listening, and keep training your confidence.",
        "I will see you in the next Cindy English practice.",
    ]
    return "\n".join(lines)


def build_visual_prompts() -> dict[str, str]:
    shared = (
        "Create one 16:9 premium 2D illustration for an English shadowing YouTube learning video. "
        "This single visual must work as both the YouTube/Facebook thumbnail and the fixed main image inside the video. "
        "Show Cindy as a blonde female English learning host in a dominant portrait composition, wearing large modern headphones. "
        "Cindy has closed eyes, a calm confident face, elegant clean features, a serene focused expression, and a premium modern look. "
        "Use a warm orange sunset, golden yellow, and warm amber background with dark navy, deep brown, or dark blue accents for contrast. "
        "The style should feel close to successful English listening and shadowing video thumbnails: strong portrait, warm colors, clean premium learning look, very visual and clickable. "
        "Add a bold readable headline with large high-contrast text: STOP FREEZING / SPEAK ENGLISH. "
        "Keep the composition strong but not crowded, with clean negative space and a clear bottom safe area reserved for animated waveform and subtitles that will be added later by the video renderer. "
        "Do not draw, illustrate, render, or include any waveform, audio bars, soundwave, equalizer, subtitles, captions, or UI elements inside the image. "
        "No 3D cartoon, no photorealistic humans, no live-action look, no realistic skin texture, no watermark, no tiny text, no logo."
    )
    return {
        "Prompt Image": shared,
        "Prompt Thumbnail": shared,
    }
